# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml


# using Radium development dedicated image
image: stormirit/radium_dev:latest

#https://docs.gitlab.com/ee/ci/yaml/#extends
.branches_with_ci:
  only:
    - master

stages:
  - build
  - test
  - doc

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build/

# artifacts:
#     # key: ${CI_COMMIT_REF_SLUG}
#     expire_in: 30 days
#     paths:
# #      - build/_deps/
#       - build/
      
build:
  stage: build
#  before_script:
#    - export PATH=$PATH:/opt/Qt/5.10.0/gcc_64/bin
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DHUB_ENABLE_TESTS=ON ..
    - cmake --build . --config Release
  


#  artifacts:
#    paths:
#      - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  
  script:
    - cd build/tests
    - ctest -V
#    - ./runmytests.sh

doc:
  stage: doc
  
  script:
    - cd build
    - cmake --build . --target docs
#    - ./runmytests.sh

