#! /bin/bash -e


headers=("-" "*" "#")

echo "
..
	generated by generateExamplesRst.sh script on : $(date)

Examples
========

Most of the examples in the examples \`directory <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/tree/master/examples>\`__.


"

printHeaders() {
	title=$1
	level=$2
	if [ $level -gt 2 ]; then
		echo "level must be between 0 and 2"
		echo "level=$level"
		exit 3
	fi
	# echo "title = '$title'"
	# echo "level = '$level'"
	if ! expr $level + 1 > /dev/null; then
		echo "level : $level is not number"
		exit 1
	fi

	strLength=$(expr length "$title")
	# echo "strLength = $strLength"

	echo
	echo $title
	# echo "headers = $headers"
	for i in `seq 1 $strLength`; do
		echo -n "${headers[$level]}"
	done
	echo
	echo
}

# printHeaders "\`$index-$exampleName <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/blob/documentation/examples/$exampleFile>\`__" 0
# exit 0

parseDir() {
	if [ ! -d "$1" ]; then
		echo "$1 is not a dir"
	fi
	dir=$1
	depth=$2
	if ! expr $depth + 1 > /dev/null; then
		exit 2
	fi

	for exampleFile in $(find $dir -maxdepth 1 -mindepth 1 | sort); do
		dir=$1
		depth=$2

		exampleName=$(basename $exampleFile | cut -d. -f1 | cut -d- -f1 --complement)
		extension=$(basename $exampleFile | cut -d. -f2)


		# echo $extension

		if [ $extension == "txt" ]; then
			continue
		fi

		# echo $exampleName

		if [ -d $exampleFile ]; then
			if [ -e $exampleFile/main.cpp ]; then
				exampleFile=$exampleFile/main.cpp
			else

				printHeaders $exampleName $depth
				parseDir $exampleFile $(expr $depth + 1)
				continue
			fi
		fi

		# echo "exampleName=$exampleName"
		# echo "extension=$extension"

		if ! cat $exampleFile | grep 'return 0' > /dev/null; then
			echo "return 0 not found in $exampleFile"
			exit 1
		fi
		if ! cat $exampleFile | grep '\\file' > /dev/null; then
			echo "\file not found in $exampleFile"
			exit 1
		fi

		exampleFile=$(echo $exampleFile | cut -c1-18 --complement)

		# echo "exampleFile=$exampleFile"

		index=$iExample
		if [ $iExample -lt 10 ]; then
			index="0$iExample"
		fi

		echo

		printHeaders "\`$index-$exampleName <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/blob/documentation/examples/$exampleFile>\`__" "$depth"

		printHeaders "Includes" "$(expr $depth + 1)"

#         echo "
# \`$index-$exampleName <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/blob/documentation/examples/$exampleFile>\`__
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# Includes
# ********

		echo "
.. literalinclude:: ../../../examples/$exampleFile
   :language: cpp
   :end-before: \file
"

		printHeaders "Source Code" "$(expr $depth + 1)"
		# Source Code
		# ***********

		echo "
.. doxygenfile:: $exampleFile

.. literalinclude:: ../../../examples/$exampleFile
   :language: cpp
   :start-after: main(
   :end-before: return 0
   :tab-width: 2
"

		iExample=$(expr $iExample + 1)
		
	done
}

iExample=0

parseDir "../../../examples" 0

