#! /bin/bash -e


echo "
..
	generated by generateExamplesRst.sh script on : $(date)

Examples
========

Most of the examples in the examples \`directory <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/tree/master/examples>\`__.


"


for exampleFile in $(ls ../../../examples/*.cpp); do
	exampleName=$(basename $exampleFile | cut -d. -f1)

	if ! cat $exampleFile | grep 'return 0' > /dev/null; then
		echo "return 0 not found in $exampleFile"
		exit 1
	fi
	if ! cat $exampleFile | grep '\\file' > /dev/null; then
		echo "\file not found in $exampleFile"
		exit 1
	fi

	echo "
\`example-$exampleName <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/blob/documentation/examples/$exampleName.cpp>\`__
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Includes
********

.. literalinclude:: ../../../examples/$exampleName.cpp
   :language: cpp
   :linenos:
   :end-before: \file

Source Code
***********

.. doxygenfile:: $exampleName.cpp

.. literalinclude:: ../../../examples/$exampleName.cpp
   :language: cpp
   :linenos:
   :start-after: main()
   :end-before: return 0
   :tab-width: 2


"
done
