#! /bin/bash -e


echo "
..
	generated by generateExamplesRst.sh script on : $(date)

Examples
========

Most of the examples in the examples \`directory <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/tree/master/examples>\`__.


"


iExample=0
for exampleFile in $(find ../../../examples -maxdepth 1 -mindepth 1 | sort); do
	exampleName=$(basename $exampleFile | cut -d. -f1 | cut -d- -f1 --complement)
	extension=$(basename $exampleFile | cut -d. -f2)

	# echo $extension

	if [ $extension == "txt" ]; then
		continue
	fi

	# echo $exampleName

	if [ -d $exampleFile ]; then
		exampleFile=$exampleFile/main.cpp
	fi

	if ! cat $exampleFile | grep 'return 0' > /dev/null; then
		echo "return 0 not found in $exampleFile"
		exit 1
	fi
	if ! cat $exampleFile | grep '\\file' > /dev/null; then
		echo "\file not found in $exampleFile"
		exit 1
	fi

	exampleFile=$(echo $exampleFile | cut -c1-18 --complement)

	# echo "exampleFile:$exampleFile"

	index=$iExample
	if [ $iExample -lt 10 ]; then
		index="0$iExample"
	fi

	echo "
\`$index-$exampleName <https://gitlab.irit.fr/storm/repos/projects/private/dcs/plateforme-experimentale/hub/-/blob/documentation/examples/$exampleFile>\`__
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Includes
********

.. literalinclude:: ../../../examples/$exampleFile
   :language: cpp
   :end-before: \file

Source Code
***********

.. doxygenfile:: $exampleFile

.. literalinclude:: ../../../examples/$exampleFile
   :language: cpp
   :start-after: main(
   :end-before: return 0
   :tab-width: 2


"

	iExample=$(expr $iExample + 1)
	
done
