
if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[0m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()



function(custom_target_added name)
#    get_property(old_count GLOBAL PROPERTY N_DEPENDENCY)
#    math( EXPR new_count "${old_count}+1" )
#    set_property(GLOBAL PROPERTY N_DEPENDENCY "${new_count}")

    get_property(old_list GLOBAL PROPERTY CUSTOM_TARGETS_FOUNDED)
#    if (${old_count} STREQUAL "0")
#        set(new_list "${name}")
#    else()
        set(new_list "${old_list} ${name}")
#    endif()
    set_property(GLOBAL PROPERTY CUSTOM_TARGETS_FOUNDED "${new_list}")
endfunction()
