
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      os:
        type: string
        required: true
      build-type:
        type: string
        required: true
      cc:
        type: string
        required: true
      cxx:
        type: string
        required: true
      icon:
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/cache@v3
      with:
        path: "${{github.workspace}}/"
        key: abc

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ inputs.cc }} -DCMAKE_CXX_COMPILER=${{ inputs.cxx }}
                -DCMAKE_BUILD_TYPE=${{inputs.build-type}} -DCMAKE_INSTALL_PREFIX=install -DHUB_ENABLE_TESTS=ON -DHUB_ENABLE_EXAMPLES=ON

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{inputs.build-type}}

    - name: Install
      run: cmake --install "${{github.workspace}}/build" --config ${{inputs.build-type}}

  test:
    needs: build
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/cache@v3
      with:
        path: "${{github.workspace}}/"
        key: abc

    - name: Test
      run: cmake --build "${{github.workspace}}/build" --target hub-tests-bin
      timeout-minutes: 5
  
