
name: Build and test

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", icon: "Windows"}
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", icon: "Linux" }
          # - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", icon: "Apple" }

    steps:
    - uses: actions/checkout@v4

    - name: Cache dir
      uses: actions/cache@v4
      with:
        path: cacheDir
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}


    - name: Mkdir and ls
      run: mkdir -p cacheDir && ls

    - name: echo
      run: echo "bonjour" >> cacheDir/test.txt

    - name: cat
      run: cat cacheDir/test.txt

    # - name: Configure CMake
    #   run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
    #             -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=install -DHUB_ENABLE_TESTS=ON -DHUB_ENABLE_EXAMPLES=ON
    #
    # - name: Build
    #   run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
    #
    # - name: Install
    #   run: cmake --install "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
    #
    # - name: Test
    #   run: cmake --build "${{github.workspace}}/build" --target hub-tests-bin
    #
