
name: Code Analysis

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  cppCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cppCheck
      run: sudo apt install -y cppcheck
         
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build"
      
    - name: CppCheck
      run: 
        cppcheck --version &&
        cmake --build ${{github.workspace}}/build --target hub-cppCheck

