
name: Deploy documentation

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: ssciwr/doxygen-install@v1.3.0
         
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DHUB_BUILD_DOC=ON
      
    - name: Install Sphinx and Breathe
      run:
        sudo apt install -y sphinx-doc
        && pip3 install sphinx-rtd-theme breathe sphinx-sitemap sphinx-mdinclude

    - name: Build sphinx doc
      run:
        cmake --build ${{github.workspace}}/build --target hub-doc-sphinx

    - name: Deploy doc 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{github.workspace}}/build/doc/sphinx/html # The folder the action should deploy.
        clean: true
        single-commit: true
