
name: Deploy documentation

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: ssciwr/doxygen-install@v1.3.0
         
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DHUB_BUILD_DOC=ON
      
    - name: Build doxygen doc
      run: cmake --build ${{github.workspace}}/build --target hub-doc-doxygen

    - name: Deploy doc 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{github.workspace}}/build/doc/docs_doxygen/html # The folder the action should deploy.
