
name: Deploy documentation

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: ssciwr/doxygen-install@v1.3.0
         
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DHUB_BUILD_DOC=ON
      
    - name: Build doxygen doc
      run: cmake --build ${{github.workspace}}/build --target hub-doc-doxygen

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/doc/docs_doxygen/html/annotated.html
